const pickupType = [
  "na",
  "Morph Ball",
  "Long Beam",
  "Missile Tank",
  "Bombs",
  "Ice Beam",
  "Varia",
  "Energy Tank",
  "High Jump",
  "Wave Beam",
  "Screw Attack",
  "Kraid Defeated",
  "Ridley Defeated",
  "Mother Brain Defeated",
  "escape",
  "Alpha Metroid Defeated",
  "Gamma Metroid Defeated",
  "Zeta Metroid Defeated",
  "Omega Metroid Defeated",
  "Larval Metroid Defeated",
  "Metroid DNA",
  "Spider Ball",
  "Spazer Beam",
  "Plasma Beam",
  "Space Jump",
  "Spring Ball",
  "Baby Metroid",
  "Queen Metroid Defeated",
  "Arachnus Defeated",
  "Charge Beam",
  "Super Missiles",
  "Speed Booster",
  "Power Bombs",
  "Grappling Beam",
  "X-Ray Scope",
  "Gravity Suit",
  "Reserve Tank",
  "Hyper Beam",
  "Torizo Defeated",
  "Phantoon Defeated",
  "Botwoon Defeated",
  "Draygon Defeated",
  "Golden Torizo Defeated",
  "Ice Missiles",
  "Wide Beam",
  "Diffusion Effect",
  "Final Suit",
  "Security Level 0",
  "Security Level 1",
  "Security Level 2",
  "Security Level 3",
  "Security Level 4",
  "First Mission",
  "Quarantine Bay",
  "Atmospheric Stabilizer",
  "Water Pump",
  "Final Mission",
  "Diffusion Beam",
  "Seeker Missiles",
  "Energy Part",
  "Accel Charge",
  "E-Recovery Tank",
  "Grapple Beam",
  "Brug Mass Defeated",
  "System Management",
  "Breeding Room",
  "Fune and Nahime Defeated",
  "East Access",
  "King Ki Hunter Defeated",
  "Exam Center Ops",
  "Mystery Creature Defeated",
  "Goyagma Defeated",
  "Sector 2 Access",
  "Ferro Crusher Defeated",
  "Deleter Hint",
  "Desert Access",
  "Rhedogian 1 Defeated",
  "Rhedogian 2 Defeated",
  "Vorash Defeated",
  "Rhedogian 3 Defeated",
  "Meeting Madeline",
  "Rhedogian 4 Defeated",
  "Nightmare 1 Defeated",
  "Sector Zero",
  "Nightmare 2 Defeated",
  "MB Defeated",
  "Post-Game",
  "Final Gauntlet Defeated",
  "Adam's Helmet",
  "Wall Jump Boots",
  "Prototype Wave Beam",
  "Containment Beam",
  "Metroid Cell Capsule",
  "Access One",
  "Access Two",
  "GF Soldier Defeated",
  "Jungle Beast Defeated",
  "Shaktool Defeated",
  "Shaktool 2.0 Defeated",
  "Alpha Metroid Defeated",
  "Chozo Hint Statue",
  "Unknown Item 1",
  "Power Grip",
  "Unknown Item 2",
  "Unknown Item 3",
  "Fully-Powered Suit",
  "Beam Beast Defeated",
  "Acid Worm Defeated",
  "Ziplines",
  "Kiru Giru Defeated",
  "Imago Defeated",
  "Ruins Test Defeated",
  "Mecha Ridley Defeated",
  "Powered Suit Samus",
  "Zero Suit Samus",
  "Ancient Power Suit Samus",
  "Scan Pulse",
  "Lightning Shield",
  "Beam Burst",
  "Phase Drift",
  "Aeion Tank",
  "Diggernaut Defeated",
  "Power Orbs Activated",
  "Power Orb Key #1",
  "Power Orb Key #2",
  "Ancient Guardian Defeated",
  "The Tester Defeated",
  "Chozo Tank Defeated",
  "Serris Defeated",
  "Tower Power",
  "Power Core Destroyed",
  "Nest Cleared",
  "Boost Ball",
  "Space Jump Boots",
  "Thermal Visor",
  "Wavebuster",
  "Ice Spreader",
  "X-Ray Visor",
  "Flamethrower",
  "Phazon Suit",
  "Chozo Artifact",
  "Parasite Queen Defeated",
  "Hive Totem Defeated",
  "Plated Beetle Defeated",
  "Incinerator Drone Defeated",
  "Flaahgra Defeated",
  "Thardus Defeated",
  "Cloaked Drone Defeated",
  "Phazon Elite Defeated",
  "Omega Pirate Defeated",
  "Meta Ridley Defeated",
  "Metroid Prime Defeated",
  "Metroid Prime (Core) Defeated",
  "Force Ball",
  "Unknown Item",
  "Violet Translator Module",
  "Amber Translator Module",
  "Dark Beam",
  "Light Beam",
  "Dark Agon Key",
  "Dark Suit",
  "Emerald Translator Module",
  "Seeker Launcher",
  "Darkburst",
  "Gravity Boost",
  "Dark Torvus Key",
  "Dark Visor",
  "Cobalt Translator Module",
  "Sunburst",
  "Echo Visor",
  "Ing Hive Key",
  "Annihilator Beam",
  "Sonic Boom",
  "Light Suit",
  "Sky Temple Key",
  "Beam Ammo Expansion",
  "Alpha Splinter Defeated",
  "Bomb Guardian Defeated",
  "Jump Guardian Defeated",
  "Missile Trooper Defeated",
  "Dark Samus 1 Defeated",
  "Amorbis Defeated",
  "Pirate Ambush Defeated",
  "Boost Guardian Defeated",
  "Grapple Guardian Defeated",
  "Alpha Blogg Defeated",
  "Chykka Defeated",
  "Quad Defeated",
  "Spider Guardian Defeated",
  "Power Bomb Guardian Defeated",
  "Dark Samus 2 Defeated",
  "Caretaker Class Drone Defeated",
  "Quadraxis Defeated",
  "Emperor Ing Defeated",
  "Dark Samus 3 and 4 Defeated",
  "GFMC Cutscene",
  "Interdimensional Bomb Slot",
  "Pirate Facility Access",
  "Vigilance Class Turret",
  "Dark Agon Energy",
  "Light of Aether (Agon)",
  "Lagoon Bridge",
  "Interdimensional Spinner",
  "Temple Cannon",
  "Scan Node",
  "Crypt Access",
  "Dark Torvus Energy",
  "Light of Aether (Torvus)",
  "Wind Chamber Access",
  "Ing Hive Energy",
  "Light of Aether (Sanctuary)",
  "Sky Temple Energy",
  "Light of Aether (Temple)",
  "Battlehammer",
  "Volt Driver",
  "Shock Coil",
  "Judicator",
  "Magmaul",
  "Imperialist",
  "Omega Cannon",
  "UA Expansion",
  "Shield Key",
  "Alimbic Artifact - CA1",
  "Octolith",
  "Alimbic Artifact - ALI1",
  "Alimbic Artifact - VDO1",
  "Alimbic Artifact - ARC1",
  "Alimbic Artifact - CA2",
  "Alimbic Artifact - ALI2",
  "Alimbic Artifact - VDO2",
  "Alimbic Artifact - ARC2",
  "Spire Event",
  "Magma Spawn Defeated",
  "Arctic Spawn Defeated",
  "Infinity Void Opened",
  "Cretaphid 1 Defeated",
  "Slench 1 Defeated",
  "Cretaphid 2 Defeated",
  "Slench 2 Defeated",
  "Cretaphid 3 Defeated",
  "Slench 3 Defeated",
  "Cretaphid 4 Defeated",
  "Slench 4 Defeated",
  "Gorea 1 Defeated",
  "Gorea 2 Defeated",
  "Grapple Lasso",
  "PED Suit",
  "Ship Missiles",
  "Hyper Ball",
  "Ship Grapple",
  "Hyper Missile",
  "Grapple Voltage",
  "Hazard Shield",
  "Nova Beam",
  "Hyper Grapple",
  "Gold Credit",
  "Energy Cell",
  "Berserker Lord Defeated",
  "Rundas Defeated",
  "Pirate Hussar & Korakk Beast Defeated",
  "Mogenar Defeated",
  "Steamlord Defeated",
  "Defense Drone Defeated",
  "Ghor Defeated",
  "Metroid Hatcher Defeated",
  "Helios Defeated",
  "Gandrayda Defeated",
  "Phazon Harvester Defeated",
  "Pirate Commander Defeated",
  "Omega Ridley Defeated",
  "Leviathan Infant Defeated",
  "Final Dark Samus Defeated",
  "Aurora Unit 313 Defeated",
  "Mission Briefing",
  "Lab Access Breach",
  "Dock A Access",
  "Generator A",
  "Generator B",
  "Generator C",
  "Save Event",
  "Bryyo Mission",
  "Fire Access",
  "Thorn Jungle Access",
  "Shield Destroyed",
  "Turret Destroyed",
  "Fed Dock",
  "Ghor Event",
  "AU Online",
  "Site A Access",
  "Valhalla Access",
  "Site B Access",
  "Theronian Bomb Part 1",
  "Xenoresearch Cells Open",
  "Theronian Bomb Part 2",
  "Theronian Bomb Part 3",
  "Theronian Bomb Complete",
  "Escape Pod",
  "Shield Down",
  "Pirate Homeworld Access",
  "Fans Off",
  "Access to Research",
  "Scrap Access",
  "Metroids Loose",
  "Mine Loop Open",
  "Shield Core Down",
  "Seed Door",
  "Hidden Court Grapple",
  "Bridge Access A",
  "Large Generator",
  "Golem Head",
  "Bridge Access B",
  "Dock B Access",
  "Mines Unlocked",
  "Pirate Leviathan Code",
  "Phaaze Mission"
];